name: .NET CI

on: [push, pull_request]

jobs:
  build:
    name: .Net ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        framework: ['6.0', '5.0', '3.1']
        include:
        - os: windows-latest
          target: win-x64
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.framework }}

    - name: Install dependencies for ${{ matrix.target }}
      run: dotnet restore -r ${{ matrix.target }}

    - name: Build ${{ matrix.target }}
      run: dotnet publish --framework ${{ matrix.framework }} -r ${{ matrix.target }} -c release -o "${{ github.workspace }}/builds/${{ matrix.framework }}/${{ matrix.target }}"

    - name: Upload ${{ matrix.target }} Build
      uses: actions/upload-artifact@v2
      with:
        name: LocalAdmin-${{ matrix.target }}-${{ matrix.framework }}
        path: ${{ github.workspace }}/builds/${{ matrix.framework }}/${{ matrix.target }}

    - name: Upload ${{ matrix.target }} Build to bundle
      uses: actions/upload-artifact@v2
      with:
        name: LocalAdmin-all-${{ matrix.framework }}
        path: ${{ github.workspace }}/builds/${{ matrix.framework }}
